[project]
name = "sql-agent-test"
version = "0.1.0"
description = "A simple agent that answers questions about a small table or generates and executes SQL queries on a SQLite Chinook database."
authors = [
    {name="Your Name", email="your.email@example.com"}
]
readme = "README.md"
requires-python = ">=3.9.0,<4.0"
dependencies = [
    "langchain >= 0.3.17",
    "langchain-community >= 0.1.3",
    "langchain-openai >= 0.3.3",
    "python-dotenv >= 1.0.0",
    "sqlalchemy >= 1.4.0",
    "pydantic >= 2.0"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
